<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Mocha.Transport.Nats</AssemblyName>
    <RootNamespace>Mocha.Transport.Nats</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mocha.Abstractions\Mocha.Abstractions.csproj" />
    <ProjectReference Include="..\Mocha\Mocha.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
    <PackageReference Include="NATS.Client.Core" />
    <PackageReference Include="NATS.Client.JetStream" />
    <PackageReference Include="NATS.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="System.IO.Hashing" />
  </ItemGroup>
</Project>
